# -*- coding: utf-8 -*-
"""
离线抽取数据（B 部分：后 12 个源文件）。
结构同 curated_data_a.py。
"""
from curated_data_a import DRUG, DISEASE, SYMPTOM, COMPANY, MECH, SE, CONCEPT

DATA_B = {
    "ibuprofen.txt": {
        "entities": [
            {"name": "布洛芬", "type": DRUG},
            {"name": "非甾体抗炎药", "type": CONCEPT},
            {"name": "丙酸类", "type": CONCEPT},
            {"name": "环氧合酶", "type": MECH},
            {"name": "前列腺素", "type": CONCEPT},
            {"name": "花生四烯酸", "type": CONCEPT},
            {"name": "头痛", "type": SYMPTOM},
            {"name": "牙痛", "type": SYMPTOM},
            {"name": "痛经", "type": SYMPTOM},
            {"name": "肌肉疼痛", "type": SYMPTOM},
            {"name": "关节疼痛", "type": SYMPTOM},
            {"name": "发热", "type": SYMPTOM},
            {"name": "骨关节炎", "type": DISEASE},
            {"name": "类风湿关节炎", "type": DISEASE},
            {"name": "关节肿胀", "type": SYMPTOM},
            {"name": "胃肠道不适", "type": SE},
            {"name": "胃痛", "type": SE},
            {"name": "恶心", "type": SE},
            {"name": "消化不良", "type": SE},
            {"name": "胃溃疡", "type": DISEASE},
            {"name": "肾功能损害", "type": DISEASE},
            {"name": "皮疹", "type": SE},
            {"name": "布洛芬缓释胶囊", "type": DRUG},
            {"name": "阿司匹林", "type": DRUG},
            {"name": "百时美施贵宝公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "布洛芬", "target": "环氧合酶", "type": "作用于"},
            {"source": "布洛芬", "target": "前列腺素", "type": "作用于"},
            {"source": "布洛芬", "target": "头痛", "type": "缓解"},
            {"source": "布洛芬", "target": "牙痛", "type": "缓解"},
            {"source": "布洛芬", "target": "痛经", "type": "缓解"},
            {"source": "布洛芬", "target": "肌肉疼痛", "type": "缓解"},
            {"source": "布洛芬", "target": "关节疼痛", "type": "缓解"},
            {"source": "布洛芬", "target": "发热", "type": "缓解"},
            {"source": "布洛芬", "target": "骨关节炎", "type": "治疗"},
            {"source": "布洛芬", "target": "类风湿关节炎", "type": "治疗"},
            {"source": "布洛芬", "target": "关节肿胀", "type": "缓解"},
            {"source": "布洛芬", "target": "胃肠道不适", "type": "副作用"},
            {"source": "布洛芬", "target": "胃痛", "type": "副作用"},
            {"source": "布洛芬", "target": "恶心", "type": "副作用"},
            {"source": "布洛芬", "target": "消化不良", "type": "副作用"},
            {"source": "布洛芬", "target": "胃溃疡", "type": "副作用"},
            {"source": "布洛芬", "target": "肾功能损害", "type": "副作用"},
            {"source": "布洛芬", "target": "皮疹", "type": "副作用"},
            {"source": "布洛芬", "target": "非甾体抗炎药", "type": "属于"},
            {"source": "布洛芬缓释胶囊", "target": "布洛芬", "type": "属于"},
            {"source": "布洛芬缓释胶囊", "target": "关节疼痛", "type": "缓解"},
            {"source": "百时美施贵宝公司", "target": "布洛芬", "type": "研发"},
        ],
    },
    "levothyroxine.txt": {
        "entities": [
            {"name": "左甲状腺素", "type": DRUG},
            {"name": "甲状腺激素", "type": CONCEPT},
            {"name": "四碘甲状腺原氨酸", "type": CONCEPT},
            {"name": "甲状腺功能减退症", "type": DISEASE},
            {"name": "基础代谢率", "type": CONCEPT},
            {"name": "乏力", "type": SYMPTOM},
            {"name": "怕冷", "type": SYMPTOM},
            {"name": "体重增加", "type": SYMPTOM},
            {"name": "皮肤干燥", "type": SYMPTOM},
            {"name": "便秘", "type": SYMPTOM},
            {"name": "甲状腺癌", "type": DISEASE},
            {"name": "甲亢", "type": DISEASE},
            {"name": "心悸", "type": SE},
            {"name": "失眠", "type": SE},
            {"name": "出汗增多", "type": SE},
            {"name": "体重下降", "type": SE},
        ],
        "relationships": [
            {"source": "左甲状腺素", "target": "甲状腺功能减退症", "type": "治疗"},
            {"source": "左甲状腺素", "target": "乏力", "type": "缓解"},
            {"source": "左甲状腺素", "target": "怕冷", "type": "缓解"},
            {"source": "左甲状腺素", "target": "体重增加", "type": "缓解"},
            {"source": "左甲状腺素", "target": "皮肤干燥", "type": "缓解"},
            {"source": "左甲状腺素", "target": "便秘", "type": "缓解"},
            {"source": "左甲状腺素", "target": "甲状腺癌", "type": "治疗"},
            {"source": "左甲状腺素", "target": "心悸", "type": "副作用"},
            {"source": "左甲状腺素", "target": "失眠", "type": "副作用"},
            {"source": "左甲状腺素", "target": "出汗增多", "type": "副作用"},
            {"source": "左甲状腺素", "target": "体重下降", "type": "副作用"},
            {"source": "左甲状腺素", "target": "甲状腺激素", "type": "属于"},
            {"source": "左甲状腺素", "target": "基础代谢率", "type": "作用于"},
            {"source": "甲亢", "target": "心悸", "type": "属于"},
        ],
    },
    "loratadine.txt": {
        "entities": [
            {"name": "氯雷他定", "type": DRUG},
            {"name": "第二代抗组胺药", "type": CONCEPT},
            {"name": "三环类", "type": CONCEPT},
            {"name": "组胺H1受体", "type": MECH},
            {"name": "组胺", "type": CONCEPT},
            {"name": "过敏性鼻炎", "type": DISEASE},
            {"name": "慢性荨麻疹", "type": DISEASE},
            {"name": "打喷嚏", "type": SYMPTOM},
            {"name": "流鼻涕", "type": SYMPTOM},
            {"name": "鼻痒", "type": SYMPTOM},
            {"name": "鼻塞", "type": SYMPTOM},
            {"name": "皮肤瘙痒", "type": SYMPTOM},
            {"name": "风团", "type": SYMPTOM},
            {"name": "血脑屏障", "type": CONCEPT},
            {"name": "嗜睡", "type": SE},
            {"name": "口干", "type": SE},
            {"name": "头痛", "type": SE},
            {"name": "乏力", "type": SE},
            {"name": "西替利嗪", "type": DRUG},
            {"name": "默沙东公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "氯雷他定", "target": "组胺H1受体", "type": "作用于"},
            {"source": "氯雷他定", "target": "过敏性鼻炎", "type": "治疗"},
            {"source": "氯雷他定", "target": "慢性荨麻疹", "type": "治疗"},
            {"source": "氯雷他定", "target": "打喷嚏", "type": "缓解"},
            {"source": "氯雷他定", "target": "流鼻涕", "type": "缓解"},
            {"source": "氯雷他定", "target": "鼻痒", "type": "缓解"},
            {"source": "氯雷他定", "target": "鼻塞", "type": "缓解"},
            {"source": "氯雷他定", "target": "皮肤瘙痒", "type": "缓解"},
            {"source": "氯雷他定", "target": "风团", "type": "缓解"},
            {"source": "氯雷他定", "target": "嗜睡", "type": "副作用"},
            {"source": "氯雷他定", "target": "口干", "type": "副作用"},
            {"source": "氯雷他定", "target": "头痛", "type": "副作用"},
            {"source": "氯雷他定", "target": "乏力", "type": "副作用"},
            {"source": "氯雷他定", "target": "第二代抗组胺药", "type": "属于"},
            {"source": "默沙东公司", "target": "氯雷他定", "type": "研发"},
            {"source": "组胺", "target": "组胺H1受体", "type": "作用于"},
            {"source": "西替利嗪", "target": "过敏性鼻炎", "type": "治疗"},
            {"source": "氯雷他定", "target": "血脑屏障", "type": "作用于"},
        ],
    },
    "losartan.txt": {
        "entities": [
            {"name": "氯沙坦", "type": DRUG},
            {"name": "血管紧张素II受体拮抗剂", "type": CONCEPT},
            {"name": "血管紧张素受体阻滞剂", "type": CONCEPT},
            {"name": "血管紧张素II受体", "type": MECH},
            {"name": "血管紧张素II", "type": CONCEPT},
            {"name": "醛固酮", "type": CONCEPT},
            {"name": "高血压", "type": DISEASE},
            {"name": "左心室肥厚", "type": DISEASE},
            {"name": "糖尿病肾病", "type": DISEASE},
            {"name": "蛋白尿", "type": SYMPTOM},
            {"name": "高尿酸血症", "type": DISEASE},
            {"name": "头晕", "type": SE},
            {"name": "乏力", "type": SE},
            {"name": "高钾血症", "type": SE},
            {"name": "干咳", "type": SE},
            {"name": "尿酸", "type": CONCEPT},
            {"name": "默沙东公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "氯沙坦", "target": "血管紧张素II受体", "type": "作用于"},
            {"source": "氯沙坦", "target": "高血压", "type": "治疗"},
            {"source": "氯沙坦", "target": "左心室肥厚", "type": "治疗"},
            {"source": "氯沙坦", "target": "糖尿病肾病", "type": "治疗"},
            {"source": "氯沙坦", "target": "蛋白尿", "type": "缓解"},
            {"source": "氯沙坦", "target": "高尿酸血症", "type": "治疗"},
            {"source": "氯沙坦", "target": "头晕", "type": "副作用"},
            {"source": "氯沙坦", "target": "乏力", "type": "副作用"},
            {"source": "氯沙坦", "target": "高钾血症", "type": "副作用"},
            {"source": "氯沙坦", "target": "干咳", "type": "副作用"},
            {"source": "氯沙坦", "target": "尿酸", "type": "作用于"},
            {"source": "氯沙坦", "target": "血管紧张素II受体拮抗剂", "type": "属于"},
            {"source": "默沙东公司", "target": "氯沙坦", "type": "研发"},
            {"source": "血管紧张素II", "target": "血管紧张素II受体", "type": "作用于"},
            {"source": "血管紧张素II", "target": "醛固酮", "type": "作用于"},
        ],
    },
    "metformin.txt": {
        "entities": [
            {"name": "二甲双胍", "type": DRUG},
            {"name": "双胍类", "type": CONCEPT},
            {"name": "一磷酸腺苷活化蛋白激酶", "type": MECH},
            {"name": "胰岛素敏感性", "type": CONCEPT},
            {"name": "肝糖异生", "type": CONCEPT},
            {"name": "胰岛素敏感性", "type": CONCEPT},
            {"name": "2型糖尿病", "type": DISEASE},
            {"name": "多囊卵巢综合征", "type": DISEASE},
            {"name": "低血糖", "type": SE},
            {"name": "腹泻", "type": SE},
            {"name": "恶心", "type": SE},
            {"name": "腹胀", "type": SE},
            {"name": "金属味", "type": SE},
            {"name": "乳酸性酸中毒", "type": SE},
            {"name": "维生素B12缺乏", "type": SE},
            {"name": "胰岛素", "type": DRUG},
            {"name": "磺脲类", "type": CONCEPT},
            {"name": "格列本脲", "type": DRUG},
        ],
        "relationships": [
            {"source": "二甲双胍", "target": "一磷酸腺苷活化蛋白激酶", "type": "作用于"},
            {"source": "二甲双胍", "target": "2型糖尿病", "type": "治疗"},
            {"source": "二甲双胍", "target": "多囊卵巢综合征", "type": "治疗"},
            {"source": "二甲双胍", "target": "肝糖异生", "type": "作用于"},
            {"source": "二甲双胍", "target": "胰岛素敏感性", "type": "作用于"},
            {"source": "二甲双胍", "target": "腹泻", "type": "副作用"},
            {"source": "二甲双胍", "target": "恶心", "type": "副作用"},
            {"source": "二甲双胍", "target": "腹胀", "type": "副作用"},
            {"source": "二甲双胍", "target": "金属味", "type": "副作用"},
            {"source": "二甲双胍", "target": "乳酸性酸中毒", "type": "副作用"},
            {"source": "二甲双胍", "target": "维生素B12缺乏", "type": "副作用"},
            {"source": "二甲双胍", "target": "双胍类", "type": "属于"},
            {"source": "胰岛素", "target": "2型糖尿病", "type": "治疗"},
            {"source": "格列本脲", "target": "2型糖尿病", "type": "治疗"},
            {"source": "磺脲类", "target": "格列本脲", "type": "属于"},
        ],
    },
    "nsaid_mechanism.txt": {
        "entities": [
            {"name": "非甾体抗炎药", "type": CONCEPT},
            {"name": "环氧合酶", "type": MECH},
            {"name": "环氧合酶1", "type": MECH},
            {"name": "环氧合酶2", "type": MECH},
            {"name": "前列腺素", "type": CONCEPT},
            {"name": "血栓素A2", "type": CONCEPT},
            {"name": "胃黏膜", "type": CONCEPT},
            {"name": "肾脏", "type": CONCEPT},
            {"name": "血小板", "type": CONCEPT},
            {"name": "炎症", "type": CONCEPT},
            {"name": "疼痛", "type": SYMPTOM},
            {"name": "发热", "type": SYMPTOM},
            {"name": "阿司匹林", "type": DRUG},
            {"name": "布洛芬", "type": DRUG},
            {"name": "对乙酰氨基酚", "type": DRUG},
            {"name": "塞来昔布", "type": DRUG},
            {"name": "选择性环氧合酶2抑制剂", "type": CONCEPT},
            {"name": "胃肠道出血", "type": SE},
            {"name": "心血管事件", "type": CONCEPT},
            {"name": "肾功能损害", "type": DISEASE},
        ],
        "relationships": [
            {"source": "非甾体抗炎药", "target": "环氧合酶", "type": "作用于"},
            {"source": "阿司匹林", "target": "环氧合酶1", "type": "作用于"},
            {"source": "阿司匹林", "target": "环氧合酶2", "type": "作用于"},
            {"source": "布洛芬", "target": "环氧合酶", "type": "作用于"},
            {"source": "对乙酰氨基酚", "target": "环氧合酶", "type": "作用于"},
            {"source": "塞来昔布", "target": "环氧合酶2", "type": "作用于"},
            {"source": "环氧合酶1", "target": "前列腺素", "type": "作用于"},
            {"source": "环氧合酶2", "target": "前列腺素", "type": "作用于"},
            {"source": "环氧合酶1", "target": "血栓素A2", "type": "作用于"},
            {"source": "环氧合酶1", "target": "胃黏膜", "type": "作用于"},
            {"source": "环氧合酶2", "target": "炎症", "type": "作用于"},
            {"source": "环氧合酶2", "target": "疼痛", "type": "作用于"},
            {"source": "环氧合酶2", "target": "发热", "type": "作用于"},
            {"source": "塞来昔布", "target": "选择性环氧合酶2抑制剂", "type": "属于"},
            {"source": "阿司匹林", "target": "胃肠道出血", "type": "副作用"},
            {"source": "布洛芬", "target": "胃肠道出血", "type": "副作用"},
            {"source": "非甾体抗炎药", "target": "肾功能损害", "type": "副作用"},
            {"source": "非甾体抗炎药", "target": "心血管事件", "type": "副作用"},
        ],
    },
    "omeprazole.txt": {
        "entities": [
            {"name": "奥美拉唑", "type": DRUG},
            {"name": "质子泵抑制剂", "type": CONCEPT},
            {"name": "苯并咪唑类", "type": CONCEPT},
            {"name": "氢钾ATP酶", "type": MECH},
            {"name": "质子泵", "type": CONCEPT},
            {"name": "胃酸", "type": CONCEPT},
            {"name": "胃溃疡", "type": DISEASE},
            {"name": "十二指肠溃疡", "type": DISEASE},
            {"name": "胃食管反流病", "type": DISEASE},
            {"name": "反酸", "type": SYMPTOM},
            {"name": "烧心", "type": SYMPTOM},
            {"name": "胃痛", "type": SYMPTOM},
            {"name": "幽门螺杆菌", "type": CONCEPT},
            {"name": "阿莫西林", "type": DRUG},
            {"name": "克拉霉素", "type": DRUG},
            {"name": "头痛", "type": SE},
            {"name": "恶心", "type": SE},
            {"name": "腹泻", "type": SE},
            {"name": "腹胀", "type": SE},
            {"name": "骨折", "type": SE},
            {"name": "低镁血症", "type": SE},
            {"name": "法莫替丁", "type": DRUG},
            {"name": "阿斯利康公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "奥美拉唑", "target": "氢钾ATP酶", "type": "作用于"},
            {"source": "奥美拉唑", "target": "胃溃疡", "type": "治疗"},
            {"source": "奥美拉唑", "target": "十二指肠溃疡", "type": "治疗"},
            {"source": "奥美拉唑", "target": "胃食管反流病", "type": "治疗"},
            {"source": "奥美拉唑", "target": "反酸", "type": "缓解"},
            {"source": "奥美拉唑", "target": "烧心", "type": "缓解"},
            {"source": "奥美拉唑", "target": "胃痛", "type": "缓解"},
            {"source": "奥美拉唑", "target": "幽门螺杆菌", "type": "治疗"},
            {"source": "奥美拉唑", "target": "胃酸", "type": "作用于"},
            {"source": "奥美拉唑", "target": "头痛", "type": "副作用"},
            {"source": "奥美拉唑", "target": "恶心", "type": "副作用"},
            {"source": "奥美拉唑", "target": "腹泻", "type": "副作用"},
            {"source": "奥美拉唑", "target": "腹胀", "type": "副作用"},
            {"source": "奥美拉唑", "target": "骨折", "type": "副作用"},
            {"source": "奥美拉唑", "target": "低镁血症", "type": "副作用"},
            {"source": "奥美拉唑", "target": "质子泵抑制剂", "type": "属于"},
            {"source": "奥美拉唑", "target": "质子泵", "type": "作用于"},
            {"source": "阿莫西林", "target": "幽门螺杆菌", "type": "治疗"},
            {"source": "克拉霉素", "target": "幽门螺杆菌", "type": "治疗"},
            {"source": "阿斯利康公司", "target": "奥美拉唑", "type": "研发"},
            {"source": "法莫替丁", "target": "胃溃疡", "type": "治疗"},
        ],
    },
    "paracetamol.txt": {
        "entities": [
            {"name": "对乙酰氨基酚", "type": DRUG},
            {"name": "扑热息痛", "type": CONCEPT},
            {"name": "解热镇痛药", "type": CONCEPT},
            {"name": "环氧合酶", "type": MECH},
            {"name": "中枢神经系统", "type": CONCEPT},
            {"name": "前列腺素", "type": CONCEPT},
            {"name": "头痛", "type": SYMPTOM},
            {"name": "牙痛", "type": SYMPTOM},
            {"name": "肌肉疼痛", "type": SYMPTOM},
            {"name": "痛经", "type": SYMPTOM},
            {"name": "关节疼痛", "type": SYMPTOM},
            {"name": "发热", "type": SYMPTOM},
            {"name": "咽痛", "type": SYMPTOM},
            {"name": "肝损伤", "type": SE},
            {"name": "肝坏死", "type": SE},
            {"name": "恶心", "type": SE},
            {"name": "皮疹", "type": SE},
            {"name": "血小板减少", "type": SE},
        ],
        "relationships": [
            {"source": "对乙酰氨基酚", "target": "环氧合酶", "type": "作用于"},
            {"source": "对乙酰氨基酚", "target": "头痛", "type": "缓解"},
            {"source": "对乙酰氨基酚", "target": "牙痛", "type": "缓解"},
            {"source": "对乙酰氨基酚", "target": "肌肉疼痛", "type": "缓解"},
            {"source": "对乙酰氨基酚", "target": "痛经", "type": "缓解"},
            {"source": "对乙酰氨基酚", "target": "关节疼痛", "type": "缓解"},
            {"source": "对乙酰氨基酚", "target": "发热", "type": "缓解"},
            {"source": "对乙酰氨基酚", "target": "咽痛", "type": "缓解"},
            {"source": "对乙酰氨基酚", "target": "肝损伤", "type": "副作用"},
            {"source": "对乙酰氨基酚", "target": "肝坏死", "type": "副作用"},
            {"source": "对乙酰氨基酚", "target": "恶心", "type": "副作用"},
            {"source": "对乙酰氨基酚", "target": "皮疹", "type": "副作用"},
            {"source": "对乙酰氨基酚", "target": "血小板减少", "type": "副作用"},
            {"source": "对乙酰氨基酚", "target": "中枢神经系统", "type": "作用于"},
            {"source": "对乙酰氨基酚", "target": "解热镇痛药", "type": "属于"},
        ],
    },
    "peptic_ulcer.txt": {
        "entities": [
            {"name": "消化性溃疡", "type": DISEASE},
            {"name": "胃溃疡", "type": DISEASE},
            {"name": "十二指肠溃疡", "type": DISEASE},
            {"name": "胃酸", "type": CONCEPT},
            {"name": "幽门螺杆菌", "type": CONCEPT},
            {"name": "非甾体抗炎药", "type": CONCEPT},
            {"name": "上腹疼痛", "type": SYMPTOM},
            {"name": "烧心", "type": SYMPTOM},
            {"name": "反酸", "type": SYMPTOM},
            {"name": "恶心", "type": SYMPTOM},
            {"name": "腹胀", "type": SYMPTOM},
            {"name": "奥美拉唑", "type": DRUG},
            {"name": "法莫替丁", "type": DRUG},
            {"name": "阿莫西林", "type": DRUG},
            {"name": "克拉霉素", "type": DRUG},
            {"name": "氢钾ATP酶", "type": MECH},
            {"name": "组胺H2受体", "type": MECH},
            {"name": "阿司匹林", "type": DRUG},
            {"name": "溃疡出血", "type": SE},
        ],
        "relationships": [
            {"source": "奥美拉唑", "target": "氢钾ATP酶", "type": "作用于"},
            {"source": "法莫替丁", "target": "组胺H2受体", "type": "作用于"},
            {"source": "奥美拉唑", "target": "胃溃疡", "type": "治疗"},
            {"source": "奥美拉唑", "target": "十二指肠溃疡", "type": "治疗"},
            {"source": "法莫替丁", "target": "胃溃疡", "type": "治疗"},
            {"source": "法莫替丁", "target": "十二指肠溃疡", "type": "治疗"},
            {"source": "奥美拉唑", "target": "上腹疼痛", "type": "缓解"},
            {"source": "奥美拉唑", "target": "烧心", "type": "缓解"},
            {"source": "奥美拉唑", "target": "反酸", "type": "缓解"},
            {"source": "奥美拉唑", "target": "幽门螺杆菌", "type": "治疗"},
            {"source": "阿莫西林", "target": "幽门螺杆菌", "type": "治疗"},
            {"source": "克拉霉素", "target": "幽门螺杆菌", "type": "治疗"},
            {"source": "胃酸", "target": "消化性溃疡", "type": "作用于"},
            {"source": "幽门螺杆菌", "target": "消化性溃疡", "type": "作用于"},
            {"source": "非甾体抗炎药", "target": "消化性溃疡", "type": "作用于"},
            {"source": "阿司匹林", "target": "溃疡出血", "type": "副作用"},
            {"source": "阿司匹林", "target": "消化性溃疡", "type": "副作用"},
        ],
    },
    "salbutamol.txt": {
        "entities": [
            {"name": "沙丁胺醇", "type": DRUG},
            {"name": "β2肾上腺素受体激动剂", "type": CONCEPT},
            {"name": "β2受体", "type": MECH},
            {"name": "环磷酸腺苷", "type": CONCEPT},
            {"name": "支气管平滑肌", "type": CONCEPT},
            {"name": "哮喘", "type": DISEASE},
            {"name": "慢性阻塞性肺疾病", "type": DISEASE},
            {"name": "支气管痉挛", "type": SYMPTOM},
            {"name": "喘息", "type": SYMPTOM},
            {"name": "气促", "type": SYMPTOM},
            {"name": "胸闷", "type": SYMPTOM},
            {"name": "咳嗽", "type": SYMPTOM},
            {"name": "心悸", "type": SE},
            {"name": "手颤", "type": SE},
            {"name": "紧张不安", "type": SE},
            {"name": "头痛", "type": SE},
            {"name": "心动过速", "type": SE},
            {"name": "吸入性糖皮质激素", "type": CONCEPT},
            {"name": "葛兰素史克公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "沙丁胺醇", "target": "β2受体", "type": "作用于"},
            {"source": "沙丁胺醇", "target": "环磷酸腺苷", "type": "作用于"},
            {"source": "沙丁胺醇", "target": "支气管平滑肌", "type": "作用于"},
            {"source": "沙丁胺醇", "target": "哮喘", "type": "治疗"},
            {"source": "沙丁胺醇", "target": "慢性阻塞性肺疾病", "type": "治疗"},
            {"source": "沙丁胺醇", "target": "支气管痉挛", "type": "缓解"},
            {"source": "沙丁胺醇", "target": "喘息", "type": "缓解"},
            {"source": "沙丁胺醇", "target": "气促", "type": "缓解"},
            {"source": "沙丁胺醇", "target": "胸闷", "type": "缓解"},
            {"source": "沙丁胺醇", "target": "咳嗽", "type": "缓解"},
            {"source": "沙丁胺醇", "target": "心悸", "type": "副作用"},
            {"source": "沙丁胺醇", "target": "手颤", "type": "副作用"},
            {"source": "沙丁胺醇", "target": "紧张不安", "type": "副作用"},
            {"source": "沙丁胺醇", "target": "头痛", "type": "副作用"},
            {"source": "沙丁胺醇", "target": "心动过速", "type": "副作用"},
            {"source": "沙丁胺醇", "target": "β2肾上腺素受体激动剂", "type": "属于"},
            {"source": "葛兰素史克公司", "target": "沙丁胺醇", "type": "研发"},
        ],
    },
    "sildenafil.txt": {
        "entities": [
            {"name": "西地那非", "type": DRUG},
            {"name": "磷酸二酯酶5抑制剂", "type": CONCEPT},
            {"name": "磷酸二酯酶5", "type": MECH},
            {"name": "环磷酸鸟苷", "type": CONCEPT},
            {"name": "一氧化氮", "type": CONCEPT},
            {"name": "血管平滑肌", "type": CONCEPT},
            {"name": "勃起功能障碍", "type": DISEASE},
            {"name": "肺动脉高压", "type": DISEASE},
            {"name": "阴茎海绵体", "type": CONCEPT},
            {"name": "肺血管阻力", "type": CONCEPT},
            {"name": "低血压", "type": SE},
            {"name": "头痛", "type": SE},
            {"name": "面部潮红", "type": SE},
            {"name": "消化不良", "type": SE},
            {"name": "鼻塞", "type": SE},
            {"name": "视觉异常", "type": SE},
            {"name": "硝酸酯类", "type": CONCEPT},
            {"name": "辉瑞公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "西地那非", "target": "磷酸二酯酶5", "type": "作用于"},
            {"source": "西地那非", "target": "环磷酸鸟苷", "type": "作用于"},
            {"source": "西地那非", "target": "勃起功能障碍", "type": "治疗"},
            {"source": "西地那非", "target": "肺动脉高压", "type": "治疗"},
            {"source": "西地那非", "target": "阴茎海绵体", "type": "作用于"},
            {"source": "西地那非", "target": "肺血管阻力", "type": "作用于"},
            {"source": "西地那非", "target": "低血压", "type": "副作用"},
            {"source": "西地那非", "target": "头痛", "type": "副作用"},
            {"source": "西地那非", "target": "面部潮红", "type": "副作用"},
            {"source": "西地那非", "target": "消化不良", "type": "副作用"},
            {"source": "西地那非", "target": "鼻塞", "type": "副作用"},
            {"source": "西地那非", "target": "视觉异常", "type": "副作用"},
            {"source": "西地那非", "target": "磷酸二酯酶5抑制剂", "type": "属于"},
            {"source": "辉瑞公司", "target": "西地那非", "type": "研发"},
            {"source": "一氧化氮", "target": "血管平滑肌", "type": "作用于"},
            {"source": "硝酸酯类", "target": "低血压", "type": "作用于"},
        ],
    },
    "type2_diabetes.txt": {
        "entities": [
            {"name": "2型糖尿病", "type": DISEASE},
            {"name": "胰岛素抵抗", "type": CONCEPT},
            {"name": "胰岛β细胞", "type": CONCEPT},
            {"name": "血糖", "type": CONCEPT},
            {"name": "多饮", "type": SYMPTOM},
            {"name": "多尿", "type": SYMPTOM},
            {"name": "多食", "type": SYMPTOM},
            {"name": "体重下降", "type": SYMPTOM},
            {"name": "乏力", "type": SYMPTOM},
            {"name": "二甲双胍", "type": DRUG},
            {"name": "磺脲类", "type": CONCEPT},
            {"name": "格列本脲", "type": DRUG},
            {"name": "胰岛素", "type": DRUG},
            {"name": "一磷酸腺苷活化蛋白激酶", "type": MECH},
            {"name": "糖尿病肾病", "type": DISEASE},
            {"name": "视网膜病变", "type": DISEASE},
            {"name": "糖尿病足", "type": DISEASE},
            {"name": "心血管疾病", "type": DISEASE},
            {"name": "高血压", "type": DISEASE},
            {"name": "高脂血症", "type": DISEASE},
        ],
        "relationships": [
            {"source": "二甲双胍", "target": "一磷酸腺苷活化蛋白激酶", "type": "作用于"},
            {"source": "二甲双胍", "target": "2型糖尿病", "type": "治疗"},
            {"source": "格列本脲", "target": "2型糖尿病", "type": "治疗"},
            {"source": "胰岛素", "target": "2型糖尿病", "type": "治疗"},
            {"source": "磺脲类", "target": "格列本脲", "type": "属于"},
            {"source": "二甲双胍", "target": "胰岛素敏感性", "type": "作用于"},
            {"source": "2型糖尿病", "target": "多饮", "type": "属于"},
            {"source": "2型糖尿病", "target": "多尿", "type": "属于"},
            {"source": "2型糖尿病", "target": "多食", "type": "属于"},
            {"source": "2型糖尿病", "target": "体重下降", "type": "属于"},
            {"source": "2型糖尿病", "target": "乏力", "type": "属于"},
            {"source": "2型糖尿病", "target": "糖尿病肾病", "type": "属于"},
            {"source": "2型糖尿病", "target": "视网膜病变", "type": "属于"},
            {"source": "2型糖尿病", "target": "糖尿病足", "type": "属于"},
            {"source": "2型糖尿病", "target": "心血管疾病", "type": "属于"},
            {"source": "高血压", "target": "2型糖尿病", "type": "属于"},
            {"source": "高脂血症", "target": "2型糖尿病", "type": "属于"},
            {"source": "2型糖尿病", "target": "胰岛素抵抗", "type": "作用于"},
        ],
    },
}
