# -*- coding: utf-8 -*-
"""
离线抽取数据（A 部分：前 12 个源文件）。
结构：{ source: {"entities": [{"name","type"}], "relationships":[{"source","target","type"}]} }
实体类型：药物/疾病/症状/公司/作用机制/副作用/概念
关系类型：研发/作用于/治疗/缓解/副作用/属于
供 build_kg_dyn.py 在无 DeepSeek key 时作为离线抽取结果。
"""

DRUG = "药物"
DISEASE = "疾病"
SYMPTOM = "症状"
COMPANY = "公司"
MECH = "作用机制"
SE = "副作用"
CONCEPT = "概念"

DATA_A = {
    "allergic_rhinitis.txt": {
        "entities": [
            {"name": "过敏性鼻炎", "type": DISEASE},
            {"name": "过敏原", "type": CONCEPT},
            {"name": "花粉", "type": CONCEPT},
            {"name": "尘螨", "type": CONCEPT},
            {"name": "动物皮屑", "type": CONCEPT},
            {"name": "霉菌", "type": CONCEPT},
            {"name": "免疫球蛋白E", "type": MECH},
            {"name": "组胺H1受体", "type": MECH},
            {"name": "氯雷他定", "type": DRUG},
            {"name": "西替利嗪", "type": DRUG},
            {"name": "布地奈德", "type": DRUG},
            {"name": "打喷嚏", "type": SYMPTOM},
            {"name": "流鼻涕", "type": SYMPTOM},
            {"name": "鼻痒", "type": SYMPTOM},
            {"name": "鼻塞", "type": SYMPTOM},
            {"name": "荨麻疹", "type": DISEASE},
            {"name": "皮肤瘙痒", "type": SYMPTOM},
            {"name": "风团", "type": SYMPTOM},
            {"name": "哮喘", "type": DISEASE},
        ],
        "relationships": [
            {"source": "氯雷他定", "target": "组胺H1受体", "type": "作用于"},
            {"source": "西替利嗪", "target": "组胺H1受体", "type": "作用于"},
            {"source": "布地奈德", "target": "过敏性鼻炎", "type": "治疗"},
            {"source": "氯雷他定", "target": "过敏性鼻炎", "type": "治疗"},
            {"source": "西替利嗪", "target": "过敏性鼻炎", "type": "治疗"},
            {"source": "氯雷他定", "target": "打喷嚏", "type": "缓解"},
            {"source": "氯雷他定", "target": "流鼻涕", "type": "缓解"},
            {"source": "氯雷他定", "target": "鼻痒", "type": "缓解"},
            {"source": "西替利嗪", "target": "鼻痒", "type": "缓解"},
            {"source": "西替利嗪", "target": "流鼻涕", "type": "缓解"},
            {"source": "西替利嗪", "target": "打喷嚏", "type": "缓解"},
            {"source": "氯雷他定", "target": "荨麻疹", "type": "治疗"},
            {"source": "氯雷他定", "target": "皮肤瘙痒", "type": "缓解"},
            {"source": "氯雷他定", "target": "风团", "type": "缓解"},
            {"source": "西替利嗪", "target": "荨麻疹", "type": "治疗"},
            {"source": "过敏原", "target": "免疫球蛋白E", "type": "作用于"},
            {"source": "花粉", "target": "过敏性鼻炎", "type": "作用于"},
            {"source": "尘螨", "target": "过敏性鼻炎", "type": "作用于"},
            {"source": "过敏性鼻炎", "target": "哮喘", "type": "属于"},
        ],
    },
    "amlodipine.txt": {
        "entities": [
            {"name": "氨氯地平", "type": DRUG},
            {"name": "二氢吡啶类", "type": CONCEPT},
            {"name": "钙通道阻滞剂", "type": CONCEPT},
            {"name": "L型钙通道", "type": MECH},
            {"name": "钙离子", "type": CONCEPT},
            {"name": "高血压", "type": DISEASE},
            {"name": "慢性稳定性心绞痛", "type": DISEASE},
            {"name": "血管痉挛性心绞痛", "type": DISEASE},
            {"name": "胸闷", "type": SYMPTOM},
            {"name": "胸痛", "type": SYMPTOM},
            {"name": "踝部水肿", "type": SE},
            {"name": "头痛", "type": SYMPTOM},
            {"name": "面部潮红", "type": SE},
            {"name": "心悸", "type": SYMPTOM},
            {"name": "眩晕", "type": SYMPTOM},
            {"name": "硝苯地平", "type": DRUG},
            {"name": "外周小动脉", "type": CONCEPT},
            {"name": "辉瑞公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "氨氯地平", "target": "L型钙通道", "type": "作用于"},
            {"source": "氨氯地平", "target": "高血压", "type": "治疗"},
            {"source": "氨氯地平", "target": "慢性稳定性心绞痛", "type": "治疗"},
            {"source": "氨氯地平", "target": "血管痉挛性心绞痛", "type": "治疗"},
            {"source": "氨氯地平", "target": "胸闷", "type": "缓解"},
            {"source": "氨氯地平", "target": "胸痛", "type": "缓解"},
            {"source": "氨氯地平", "target": "踝部水肿", "type": "副作用"},
            {"source": "氨氯地平", "target": "头痛", "type": "副作用"},
            {"source": "氨氯地平", "target": "面部潮红", "type": "副作用"},
            {"source": "氨氯地平", "target": "心悸", "type": "副作用"},
            {"source": "氨氯地平", "target": "眩晕", "type": "副作用"},
            {"source": "氨氯地平", "target": "钙通道阻滞剂", "type": "属于"},
            {"source": "辉瑞公司", "target": "氨氯地平", "type": "研发"},
            {"source": "氨氯地平", "target": "外周小动脉", "type": "作用于"},
            {"source": "硝苯地平", "target": "高血压", "type": "治疗"},
        ],
    },
    "amoxicillin.txt": {
        "entities": [
            {"name": "阿莫西林", "type": DRUG},
            {"name": "青霉素类", "type": CONCEPT},
            {"name": "β-内酰胺类", "type": CONCEPT},
            {"name": "广谱抗生素", "type": CONCEPT},
            {"name": "青霉素结合蛋白", "type": MECH},
            {"name": "肽聚糖", "type": CONCEPT},
            {"name": "克拉维酸", "type": DRUG},
            {"name": "β-内酰胺酶", "type": MECH},
            {"name": "呼吸道感染", "type": DISEASE},
            {"name": "中耳炎", "type": DISEASE},
            {"name": "鼻窦炎", "type": DISEASE},
            {"name": "尿路感染", "type": DISEASE},
            {"name": "皮肤软组织感染", "type": DISEASE},
            {"name": "幽门螺杆菌", "type": CONCEPT},
            {"name": "皮疹", "type": SE},
            {"name": "腹泻", "type": SE},
            {"name": "恶心", "type": SE},
            {"name": "过敏反应", "type": SE},
            {"name": "过敏性休克", "type": SE},
            {"name": "伪膜性肠炎", "type": SE},
            {"name": "葛兰素史克公司", "type": COMPANY},
            {"name": "阿莫西林克拉维酸钾", "type": DRUG},
        ],
        "relationships": [
            {"source": "阿莫西林", "target": "青霉素结合蛋白", "type": "作用于"},
            {"source": "阿莫西林", "target": "呼吸道感染", "type": "治疗"},
            {"source": "阿莫西林", "target": "中耳炎", "type": "治疗"},
            {"source": "阿莫西林", "target": "鼻窦炎", "type": "治疗"},
            {"source": "阿莫西林", "target": "尿路感染", "type": "治疗"},
            {"source": "阿莫西林", "target": "皮肤软组织感染", "type": "治疗"},
            {"source": "阿莫西林", "target": "幽门螺杆菌", "type": "治疗"},
            {"source": "阿莫西林", "target": "皮疹", "type": "副作用"},
            {"source": "阿莫西林", "target": "腹泻", "type": "副作用"},
            {"source": "阿莫西林", "target": "恶心", "type": "副作用"},
            {"source": "阿莫西林", "target": "过敏反应", "type": "副作用"},
            {"source": "阿莫西林", "target": "过敏性休克", "type": "副作用"},
            {"source": "阿莫西林", "target": "伪膜性肠炎", "type": "副作用"},
            {"source": "阿莫西林", "target": "青霉素类", "type": "属于"},
            {"source": "葛兰素史克公司", "target": "阿莫西林", "type": "研发"},
            {"source": "克拉维酸", "target": "β-内酰胺酶", "type": "作用于"},
            {"source": "阿莫西林克拉维酸钾", "target": "阿莫西林", "type": "属于"},
            {"source": "阿莫西林克拉维酸钾", "target": "呼吸道感染", "type": "治疗"},
        ],
    },
    "aspirin.txt": {
        "entities": [
            {"name": "阿司匹林", "type": DRUG},
            {"name": "非甾体抗炎药", "type": CONCEPT},
            {"name": "水杨酸类", "type": CONCEPT},
            {"name": "环氧合酶", "type": MECH},
            {"name": "环氧合酶1", "type": MECH},
            {"name": "环氧合酶2", "type": MECH},
            {"name": "前列腺素", "type": CONCEPT},
            {"name": "血栓素A2", "type": CONCEPT},
            {"name": "花生四烯酸", "type": CONCEPT},
            {"name": "血小板聚集", "type": CONCEPT},
            {"name": "头痛", "type": SYMPTOM},
            {"name": "牙痛", "type": SYMPTOM},
            {"name": "肌肉疼痛", "type": SYMPTOM},
            {"name": "关节疼痛", "type": SYMPTOM},
            {"name": "发热", "type": SYMPTOM},
            {"name": "类风湿关节炎", "type": DISEASE},
            {"name": "骨关节炎", "type": DISEASE},
            {"name": "关节肿胀", "type": SYMPTOM},
            {"name": "心肌梗死", "type": DISEASE},
            {"name": "缺血性脑卒中", "type": DISEASE},
            {"name": "冠心病", "type": DISEASE},
            {"name": "胃肠道出血", "type": SE},
            {"name": "恶心", "type": SE},
            {"name": "胃痛", "type": SE},
            {"name": "消化不良", "type": SE},
            {"name": "耳鸣", "type": SE},
            {"name": "过敏反应", "type": SE},
            {"name": "支气管痉挛", "type": SYMPTOM},
            {"name": "拜耳公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "阿司匹林", "target": "环氧合酶", "type": "作用于"},
            {"source": "阿司匹林", "target": "环氧合酶1", "type": "作用于"},
            {"source": "阿司匹林", "target": "环氧合酶2", "type": "作用于"},
            {"source": "阿司匹林", "target": "前列腺素", "type": "作用于"},
            {"source": "阿司匹林", "target": "血栓素A2", "type": "作用于"},
            {"source": "阿司匹林", "target": "血小板聚集", "type": "作用于"},
            {"source": "阿司匹林", "target": "头痛", "type": "治疗"},
            {"source": "阿司匹林", "target": "发热", "type": "缓解"},
            {"source": "阿司匹林", "target": "牙痛", "type": "缓解"},
            {"source": "阿司匹林", "target": "肌肉疼痛", "type": "缓解"},
            {"source": "阿司匹林", "target": "关节疼痛", "type": "缓解"},
            {"source": "阿司匹林", "target": "类风湿关节炎", "type": "治疗"},
            {"source": "阿司匹林", "target": "骨关节炎", "type": "治疗"},
            {"source": "阿司匹林", "target": "关节肿胀", "type": "缓解"},
            {"source": "阿司匹林", "target": "心肌梗死", "type": "治疗"},
            {"source": "阿司匹林", "target": "缺血性脑卒中", "type": "治疗"},
            {"source": "阿司匹林", "target": "冠心病", "type": "治疗"},
            {"source": "阿司匹林", "target": "胃肠道出血", "type": "副作用"},
            {"source": "阿司匹林", "target": "恶心", "type": "副作用"},
            {"source": "阿司匹林", "target": "胃痛", "type": "副作用"},
            {"source": "阿司匹林", "target": "消化不良", "type": "副作用"},
            {"source": "阿司匹林", "target": "耳鸣", "type": "副作用"},
            {"source": "阿司匹林", "target": "过敏反应", "type": "副作用"},
            {"source": "阿司匹林", "target": "支气管痉挛", "type": "副作用"},
            {"source": "阿司匹林", "target": "非甾体抗炎药", "type": "属于"},
            {"source": "拜耳公司", "target": "阿司匹林", "type": "研发"},
            {"source": "环氧合酶", "target": "前列腺素", "type": "作用于"},
            {"source": "花生四烯酸", "target": "前列腺素", "type": "作用于"},
        ],
    },
    "asthma_overview.txt": {
        "entities": [
            {"name": "哮喘", "type": DISEASE},
            {"name": "气道慢性炎症", "type": CONCEPT},
            {"name": "气道高反应性", "type": CONCEPT},
            {"name": "气道平滑肌", "type": CONCEPT},
            {"name": "支气管狭窄", "type": SYMPTOM},
            {"name": "喘息", "type": SYMPTOM},
            {"name": "气促", "type": SYMPTOM},
            {"name": "胸闷", "type": SYMPTOM},
            {"name": "咳嗽", "type": SYMPTOM},
            {"name": "沙丁胺醇", "type": DRUG},
            {"name": "布地奈德", "type": DRUG},
            {"name": "β2受体", "type": MECH},
            {"name": "吸入性糖皮质激素", "type": CONCEPT},
            {"name": "过敏性鼻炎", "type": DISEASE},
            {"name": "冷空气", "type": CONCEPT},
            {"name": "运动", "type": CONCEPT},
            {"name": "尘螨", "type": CONCEPT},
            {"name": "烟雾", "type": CONCEPT},
        ],
        "relationships": [
            {"source": "沙丁胺醇", "target": "β2受体", "type": "作用于"},
            {"source": "沙丁胺醇", "target": "哮喘", "type": "治疗"},
            {"source": "沙丁胺醇", "target": "喘息", "type": "缓解"},
            {"source": "沙丁胺醇", "target": "气促", "type": "缓解"},
            {"source": "沙丁胺醇", "target": "支气管狭窄", "type": "缓解"},
            {"source": "布地奈德", "target": "哮喘", "type": "治疗"},
            {"source": "布地奈德", "target": "哮喘", "type": "作用于"},
            {"source": "布地奈德", "target": "气道慢性炎症", "type": "作用于"},
            {"source": "布地奈德", "target": "吸入性糖皮质激素", "type": "属于"},
            {"source": "过敏性鼻炎", "target": "哮喘", "type": "属于"},
            {"source": "冷空气", "target": "哮喘", "type": "作用于"},
            {"source": "运动", "target": "哮喘", "type": "作用于"},
            {"source": "尘螨", "target": "哮喘", "type": "作用于"},
            {"source": "烟雾", "target": "哮喘", "type": "作用于"},
            {"source": "哮喘", "target": "咳嗽", "type": "属于"},
            {"source": "哮喘", "target": "胸闷", "type": "属于"},
        ],
    },
    "atorvastatin.txt": {
        "entities": [
            {"name": "阿托伐他汀", "type": DRUG},
            {"name": "他汀类", "type": CONCEPT},
            {"name": "羟甲基戊二酰辅酶A还原酶", "type": MECH},
            {"name": "低密度脂蛋白胆固醇", "type": CONCEPT},
            {"name": "低密度脂蛋白受体", "type": MECH},
            {"name": "高胆固醇血症", "type": DISEASE},
            {"name": "混合型高脂血症", "type": DISEASE},
            {"name": "家族性高胆固醇血症", "type": DISEASE},
            {"name": "高脂血症", "type": DISEASE},
            {"name": "动脉粥样硬化", "type": DISEASE},
            {"name": "心肌梗死", "type": DISEASE},
            {"name": "脑卒中", "type": DISEASE},
            {"name": "肌肉疼痛", "type": SE},
            {"name": "肝酶升高", "type": SE},
            {"name": "头痛", "type": SE},
            {"name": "消化不良", "type": SE},
            {"name": "横纹肌溶解", "type": SE},
            {"name": "瑞舒伐他汀", "type": DRUG},
            {"name": "辉瑞公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "阿托伐他汀", "target": "羟甲基戊二酰辅酶A还原酶", "type": "作用于"},
            {"source": "阿托伐他汀", "target": "高胆固醇血症", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "混合型高脂血症", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "家族性高胆固醇血症", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "高脂血症", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "动脉粥样硬化", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "心肌梗死", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "脑卒中", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "肌肉疼痛", "type": "副作用"},
            {"source": "阿托伐他汀", "target": "肝酶升高", "type": "副作用"},
            {"source": "阿托伐他汀", "target": "头痛", "type": "副作用"},
            {"source": "阿托伐他汀", "target": "消化不良", "type": "副作用"},
            {"source": "阿托伐他汀", "target": "横纹肌溶解", "type": "副作用"},
            {"source": "阿托伐他汀", "target": "低密度脂蛋白胆固醇", "type": "作用于"},
            {"source": "阿托伐他汀", "target": "他汀类", "type": "属于"},
            {"source": "辉瑞公司", "target": "阿托伐他汀", "type": "研发"},
            {"source": "瑞舒伐他汀", "target": "高脂血症", "type": "治疗"},
        ],
    },
    "cardiovascular_overview.txt": {
        "entities": [
            {"name": "动脉粥样硬化性心血管疾病", "type": DISEASE},
            {"name": "心肌梗死", "type": DISEASE},
            {"name": "脑卒中", "type": DISEASE},
            {"name": "冠状动脉粥样硬化性心脏病", "type": DISEASE},
            {"name": "高血压", "type": DISEASE},
            {"name": "高脂血症", "type": DISEASE},
            {"name": "糖尿病", "type": DISEASE},
            {"name": "吸烟", "type": CONCEPT},
            {"name": "肥胖", "type": CONCEPT},
            {"name": "阿司匹林", "type": DRUG},
            {"name": "氯吡格雷", "type": DRUG},
            {"name": "阿托伐他汀", "type": DRUG},
            {"name": "氨氯地平", "type": DRUG},
            {"name": "氯沙坦", "type": DRUG},
            {"name": "二甲双胍", "type": DRUG},
            {"name": "血小板聚集", "type": CONCEPT},
            {"name": "低密度脂蛋白胆固醇", "type": CONCEPT},
        ],
        "relationships": [
            {"source": "阿司匹林", "target": "血小板聚集", "type": "作用于"},
            {"source": "氯吡格雷", "target": "血小板聚集", "type": "作用于"},
            {"source": "阿司匹林", "target": "心肌梗死", "type": "治疗"},
            {"source": "阿司匹林", "target": "脑卒中", "type": "治疗"},
            {"source": "氯吡格雷", "target": "心肌梗死", "type": "治疗"},
            {"source": "氯吡格雷", "target": "脑卒中", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "低密度脂蛋白胆固醇", "type": "作用于"},
            {"source": "阿托伐他汀", "target": "动脉粥样硬化性心血管疾病", "type": "治疗"},
            {"source": "氨氯地平", "target": "高血压", "type": "治疗"},
            {"source": "氯沙坦", "target": "高血压", "type": "治疗"},
            {"source": "二甲双胍", "target": "糖尿病", "type": "治疗"},
            {"source": "高血压", "target": "心肌梗死", "type": "属于"},
            {"source": "高脂血症", "target": "心肌梗死", "type": "属于"},
            {"source": "糖尿病", "target": "心肌梗死", "type": "属于"},
            {"source": "吸烟", "target": "心肌梗死", "type": "属于"},
            {"source": "肥胖", "target": "心肌梗死", "type": "属于"},
            {"source": "高脂血症", "target": "动脉粥样硬化", "type": "作用于"},
        ],
    },
    "cetirizine.txt": {
        "entities": [
            {"name": "西替利嗪", "type": DRUG},
            {"name": "第二代抗组胺药", "type": CONCEPT},
            {"name": "哌嗪类", "type": CONCEPT},
            {"name": "组胺H1受体", "type": MECH},
            {"name": "组胺", "type": CONCEPT},
            {"name": "过敏性鼻炎", "type": DISEASE},
            {"name": "过敏性结膜炎", "type": DISEASE},
            {"name": "荨麻疹", "type": DISEASE},
            {"name": "鼻痒", "type": SYMPTOM},
            {"name": "喷嚏", "type": SYMPTOM},
            {"name": "流涕", "type": SYMPTOM},
            {"name": "流泪", "type": SYMPTOM},
            {"name": "嗜睡", "type": SE},
            {"name": "乏力", "type": SE},
            {"name": "口干", "type": SE},
            {"name": "头晕", "type": SE},
            {"name": "氯雷他定", "type": DRUG},
            {"name": "优时比公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "西替利嗪", "target": "组胺H1受体", "type": "作用于"},
            {"source": "西替利嗪", "target": "过敏性鼻炎", "type": "治疗"},
            {"source": "西替利嗪", "target": "过敏性结膜炎", "type": "治疗"},
            {"source": "西替利嗪", "target": "荨麻疹", "type": "治疗"},
            {"source": "西替利嗪", "target": "鼻痒", "type": "缓解"},
            {"source": "西替利嗪", "target": "喷嚏", "type": "缓解"},
            {"source": "西替利嗪", "target": "流涕", "type": "缓解"},
            {"source": "西替利嗪", "target": "流泪", "type": "缓解"},
            {"source": "西替利嗪", "target": "嗜睡", "type": "副作用"},
            {"source": "西替利嗪", "target": "乏力", "type": "副作用"},
            {"source": "西替利嗪", "target": "口干", "type": "副作用"},
            {"source": "西替利嗪", "target": "头晕", "type": "副作用"},
            {"source": "西替利嗪", "target": "第二代抗组胺药", "type": "属于"},
            {"source": "优时比公司", "target": "西替利嗪", "type": "研发"},
            {"source": "组胺", "target": "组胺H1受体", "type": "作用于"},
            {"source": "氯雷他定", "target": "过敏性鼻炎", "type": "治疗"},
        ],
    },
    "clopidogrel.txt": {
        "entities": [
            {"name": "氯吡格雷", "type": DRUG},
            {"name": "噻吩并吡啶类", "type": CONCEPT},
            {"name": "P2Y12受体", "type": MECH},
            {"name": "二磷酸腺苷", "type": CONCEPT},
            {"name": "血小板", "type": CONCEPT},
            {"name": "冠状动脉粥样硬化性心脏病", "type": DISEASE},
            {"name": "心肌梗死", "type": DISEASE},
            {"name": "缺血性脑卒中", "type": DISEASE},
            {"name": "阿司匹林", "type": DRUG},
            {"name": "出血", "type": SE},
            {"name": "鼻出血", "type": SE},
            {"name": "牙龈出血", "type": SE},
            {"name": "皮下瘀斑", "type": SE},
            {"name": "胃肠道出血", "type": SE},
            {"name": "赛诺菲公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "氯吡格雷", "target": "P2Y12受体", "type": "作用于"},
            {"source": "氯吡格雷", "target": "冠状动脉粥样硬化性心脏病", "type": "治疗"},
            {"source": "氯吡格雷", "target": "心肌梗死", "type": "治疗"},
            {"source": "氯吡格雷", "target": "缺血性脑卒中", "type": "治疗"},
            {"source": "氯吡格雷", "target": "出血", "type": "副作用"},
            {"source": "氯吡格雷", "target": "鼻出血", "type": "副作用"},
            {"source": "氯吡格雷", "target": "牙龈出血", "type": "副作用"},
            {"source": "氯吡格雷", "target": "皮下瘀斑", "type": "副作用"},
            {"source": "氯吡格雷", "target": "胃肠道出血", "type": "副作用"},
            {"source": "氯吡格雷", "target": "血小板", "type": "作用于"},
            {"source": "氯吡格雷", "target": "噻吩并吡啶类", "type": "属于"},
            {"source": "赛诺菲公司", "target": "氯吡格雷", "type": "研发"},
            {"source": "阿司匹林", "target": "心肌梗死", "type": "治疗"},
            {"source": "二磷酸腺苷", "target": "P2Y12受体", "type": "作用于"},
        ],
    },
    "famotidine.txt": {
        "entities": [
            {"name": "法莫替丁", "type": DRUG},
            {"name": "组胺H2受体拮抗剂", "type": CONCEPT},
            {"name": "组胺H2受体", "type": MECH},
            {"name": "胃壁细胞", "type": CONCEPT},
            {"name": "胃酸", "type": CONCEPT},
            {"name": "胃溃疡", "type": DISEASE},
            {"name": "十二指肠溃疡", "type": DISEASE},
            {"name": "胃食管反流病", "type": DISEASE},
            {"name": "反酸", "type": SYMPTOM},
            {"name": "烧心", "type": SYMPTOM},
            {"name": "上腹疼痛", "type": SYMPTOM},
            {"name": "头痛", "type": SE},
            {"name": "头晕", "type": SE},
            {"name": "便秘", "type": SE},
            {"name": "腹泻", "type": SE},
            {"name": "皮疹", "type": SE},
            {"name": "奥美拉唑", "type": DRUG},
            {"name": "山之内制药公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "法莫替丁", "target": "组胺H2受体", "type": "作用于"},
            {"source": "法莫替丁", "target": "胃溃疡", "type": "治疗"},
            {"source": "法莫替丁", "target": "十二指肠溃疡", "type": "治疗"},
            {"source": "法莫替丁", "target": "胃食管反流病", "type": "治疗"},
            {"source": "法莫替丁", "target": "反酸", "type": "缓解"},
            {"source": "法莫替丁", "target": "烧心", "type": "缓解"},
            {"source": "法莫替丁", "target": "上腹疼痛", "type": "缓解"},
            {"source": "法莫替丁", "target": "头痛", "type": "副作用"},
            {"source": "法莫替丁", "target": "头晕", "type": "副作用"},
            {"source": "法莫替丁", "target": "便秘", "type": "副作用"},
            {"source": "法莫替丁", "target": "腹泻", "type": "副作用"},
            {"source": "法莫替丁", "target": "皮疹", "type": "副作用"},
            {"source": "法莫替丁", "target": "胃酸", "type": "作用于"},
            {"source": "法莫替丁", "target": "组胺H2受体拮抗剂", "type": "属于"},
            {"source": "山之内制药公司", "target": "法莫替丁", "type": "研发"},
            {"source": "奥美拉唑", "target": "胃溃疡", "type": "治疗"},
        ],
    },
    "hyperlipidemia.txt": {
        "entities": [
            {"name": "高脂血症", "type": DISEASE},
            {"name": "总胆固醇", "type": CONCEPT},
            {"name": "低密度脂蛋白胆固醇", "type": CONCEPT},
            {"name": "甘油三酯", "type": CONCEPT},
            {"name": "动脉粥样硬化", "type": DISEASE},
            {"name": "血管壁斑块", "type": CONCEPT},
            {"name": "心肌梗死", "type": DISEASE},
            {"name": "缺血性脑卒中", "type": DISEASE},
            {"name": "阿托伐他汀", "type": DRUG},
            {"name": "瑞舒伐他汀", "type": DRUG},
            {"name": "依折麦布", "type": DRUG},
            {"name": "他汀类", "type": CONCEPT},
            {"name": "羟甲基戊二酰辅酶A还原酶", "type": MECH},
            {"name": "高血压", "type": DISEASE},
            {"name": "糖尿病", "type": DISEASE},
            {"name": "高脂饮食", "type": CONCEPT},
            {"name": "运动", "type": CONCEPT},
        ],
        "relationships": [
            {"source": "阿托伐他汀", "target": "羟甲基戊二酰辅酶A还原酶", "type": "作用于"},
            {"source": "阿托伐他汀", "target": "低密度脂蛋白胆固醇", "type": "作用于"},
            {"source": "阿托伐他汀", "target": "高脂血症", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "动脉粥样硬化", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "心肌梗死", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "缺血性脑卒中", "type": "治疗"},
            {"source": "瑞舒伐他汀", "target": "高脂血症", "type": "治疗"},
            {"source": "依折麦布", "target": "高脂血症", "type": "治疗"},
            {"source": "阿托伐他汀", "target": "他汀类", "type": "属于"},
            {"source": "低密度脂蛋白胆固醇", "target": "动脉粥样硬化", "type": "作用于"},
            {"source": "高脂血症", "target": "心肌梗死", "type": "属于"},
            {"source": "高血压", "target": "高脂血症", "type": "属于"},
            {"source": "糖尿病", "target": "高脂血症", "type": "属于"},
            {"source": "高脂饮食", "target": "高脂血症", "type": "作用于"},
            {"source": "运动", "target": "高脂血症", "type": "治疗"},
        ],
    },
    "hypertension_overview.txt": {
        "entities": [
            {"name": "高血压", "type": DISEASE},
            {"name": "心肌梗死", "type": DISEASE},
            {"name": "脑卒中", "type": DISEASE},
            {"name": "肾功能损害", "type": DISEASE},
            {"name": "头晕", "type": SYMPTOM},
            {"name": "头痛", "type": SYMPTOM},
            {"name": "心悸", "type": SYMPTOM},
            {"name": "乏力", "type": SYMPTOM},
            {"name": "钙通道阻滞剂", "type": CONCEPT},
            {"name": "血管紧张素II受体拮抗剂", "type": CONCEPT},
            {"name": "血管紧张素转化酶抑制剂", "type": CONCEPT},
            {"name": "利尿剂", "type": CONCEPT},
            {"name": "β受体阻滞剂", "type": CONCEPT},
            {"name": "氨氯地平", "type": DRUG},
            {"name": "氯沙坦", "type": DRUG},
            {"name": "缬沙坦", "type": DRUG},
            {"name": "依那普利", "type": DRUG},
            {"name": "卡托普利", "type": DRUG},
            {"name": "血管紧张素II受体", "type": MECH},
            {"name": "血管紧张素转化酶", "type": MECH},
        ],
        "relationships": [
            {"source": "氨氯地平", "target": "高血压", "type": "治疗"},
            {"source": "氯沙坦", "target": "高血压", "type": "治疗"},
            {"source": "缬沙坦", "target": "高血压", "type": "治疗"},
            {"source": "依那普利", "target": "高血压", "type": "治疗"},
            {"source": "卡托普利", "target": "高血压", "type": "治疗"},
            {"source": "氨氯地平", "target": "钙通道阻滞剂", "type": "属于"},
            {"source": "氯沙坦", "target": "血管紧张素II受体拮抗剂", "type": "属于"},
            {"source": "缬沙坦", "target": "血管紧张素II受体拮抗剂", "type": "属于"},
            {"source": "依那普利", "target": "血管紧张素转化酶抑制剂", "type": "属于"},
            {"source": "卡托普利", "target": "血管紧张素转化酶抑制剂", "type": "属于"},
            {"source": "氯沙坦", "target": "血管紧张素II受体", "type": "作用于"},
            {"source": "缬沙坦", "target": "血管紧张素II受体", "type": "作用于"},
            {"source": "依那普利", "target": "血管紧张素转化酶", "type": "作用于"},
            {"source": "卡托普利", "target": "血管紧张素转化酶", "type": "作用于"},
            {"source": "高血压", "target": "头晕", "type": "属于"},
            {"source": "高血压", "target": "头痛", "type": "属于"},
            {"source": "高血压", "target": "心悸", "type": "属于"},
            {"source": "高血压", "target": "心肌梗死", "type": "属于"},
            {"source": "高血压", "target": "脑卒中", "type": "属于"},
            {"source": "高血压", "target": "肾功能损害", "type": "属于"},
        ],
    },
}
