# -*- coding: utf-8 -*-
"""离线抽取数据（C 部分：后补 8 篇药物专论）。结构同 curated_data_a.py。"""
from curated_data_a import DRUG, DISEASE, SYMPTOM, COMPANY, MECH, SE, CONCEPT

DATA_C = {
    "valsartan.txt": {
        "entities": [
            {"name": "缬沙坦", "type": DRUG},
            {"name": "血管紧张素II受体拮抗剂", "type": CONCEPT},
            {"name": "沙坦类", "type": CONCEPT},
            {"name": "血管紧张素II受体", "type": MECH},
            {"name": "血管紧张素II", "type": CONCEPT},
            {"name": "醛固酮", "type": CONCEPT},
            {"name": "高血压", "type": DISEASE},
            {"name": "心力衰竭", "type": DISEASE},
            {"name": "心肌梗死", "type": DISEASE},
            {"name": "糖尿病肾病", "type": DISEASE},
            {"name": "头晕", "type": SE},
            {"name": "乏力", "type": SE},
            {"name": "高钾血症", "type": SE},
            {"name": "血管性水肿", "type": SE},
            {"name": "诺华公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "缬沙坦", "target": "血管紧张素II受体", "type": "作用于"},
            {"source": "缬沙坦", "target": "高血压", "type": "治疗"},
            {"source": "缬沙坦", "target": "心力衰竭", "type": "治疗"},
            {"source": "缬沙坦", "target": "心肌梗死", "type": "治疗"},
            {"source": "缬沙坦", "target": "糖尿病肾病", "type": "治疗"},
            {"source": "缬沙坦", "target": "头晕", "type": "副作用"},
            {"source": "缬沙坦", "target": "乏力", "type": "副作用"},
            {"source": "缬沙坦", "target": "高钾血症", "type": "副作用"},
            {"source": "缬沙坦", "target": "血管性水肿", "type": "副作用"},
            {"source": "缬沙坦", "target": "血管紧张素II受体拮抗剂", "type": "属于"},
            {"source": "诺华公司", "target": "缬沙坦", "type": "研发"},
            {"source": "血管紧张素II", "target": "血管紧张素II受体", "type": "作用于"},
            {"source": "血管紧张素II", "target": "醛固酮", "type": "作用于"},
        ],
    },
    "enalapril.txt": {
        "entities": [
            {"name": "依那普利", "type": DRUG},
            {"name": "血管紧张素转化酶抑制剂", "type": CONCEPT},
            {"name": "血管紧张素转化酶", "type": MECH},
            {"name": "血管紧张素II", "type": CONCEPT},
            {"name": "醛固酮", "type": CONCEPT},
            {"name": "高血压", "type": DISEASE},
            {"name": "心力衰竭", "type": DISEASE},
            {"name": "干咳", "type": SE},
            {"name": "头晕", "type": SE},
            {"name": "高钾血症", "type": SE},
            {"name": "血管性水肿", "type": SE},
            {"name": "默沙东公司", "type": COMPANY},
            {"name": "氯沙坦", "type": DRUG},
        ],
        "relationships": [
            {"source": "依那普利", "target": "血管紧张素转化酶", "type": "作用于"},
            {"source": "依那普利", "target": "高血压", "type": "治疗"},
            {"source": "依那普利", "target": "心力衰竭", "type": "治疗"},
            {"source": "依那普利", "target": "干咳", "type": "副作用"},
            {"source": "依那普利", "target": "头晕", "type": "副作用"},
            {"source": "依那普利", "target": "高钾血症", "type": "副作用"},
            {"source": "依那普利", "target": "血管性水肿", "type": "副作用"},
            {"source": "依那普利", "target": "血管紧张素转化酶抑制剂", "type": "属于"},
            {"source": "默沙东公司", "target": "依那普利", "type": "研发"},
            {"source": "血管紧张素转化酶", "target": "血管紧张素II", "type": "作用于"},
            {"source": "氯沙坦", "target": "高血压", "type": "治疗"},
        ],
    },
    "nifedipine.txt": {
        "entities": [
            {"name": "硝苯地平", "type": DRUG},
            {"name": "二氢吡啶类钙通道阻滞剂", "type": CONCEPT},
            {"name": "L型钙通道", "type": MECH},
            {"name": "外周小动脉", "type": CONCEPT},
            {"name": "冠状动脉", "type": CONCEPT},
            {"name": "高血压", "type": DISEASE},
            {"name": "稳定性心绞痛", "type": DISEASE},
            {"name": "头痛", "type": SE},
            {"name": "面部潮红", "type": SE},
            {"name": "踝部水肿", "type": SE},
            {"name": "心悸", "type": SE},
            {"name": "牙龈增生", "type": SE},
            {"name": "拜耳公司", "type": COMPANY},
            {"name": "氨氯地平", "type": DRUG},
        ],
        "relationships": [
            {"source": "硝苯地平", "target": "L型钙通道", "type": "作用于"},
            {"source": "硝苯地平", "target": "高血压", "type": "治疗"},
            {"source": "硝苯地平", "target": "稳定性心绞痛", "type": "治疗"},
            {"source": "硝苯地平", "target": "外周小动脉", "type": "作用于"},
            {"source": "硝苯地平", "target": "冠状动脉", "type": "作用于"},
            {"source": "硝苯地平", "target": "头痛", "type": "副作用"},
            {"source": "硝苯地平", "target": "面部潮红", "type": "副作用"},
            {"source": "硝苯地平", "target": "踝部水肿", "type": "副作用"},
            {"source": "硝苯地平", "target": "心悸", "type": "副作用"},
            {"source": "硝苯地平", "target": "牙龈增生", "type": "副作用"},
            {"source": "硝苯地平", "target": "二氢吡啶类钙通道阻滞剂", "type": "属于"},
            {"source": "拜耳公司", "target": "硝苯地平", "type": "研发"},
            {"source": "氨氯地平", "target": "高血压", "type": "治疗"},
        ],
    },
    "rosuvastatin.txt": {
        "entities": [
            {"name": "瑞舒伐他汀", "type": DRUG},
            {"name": "他汀类", "type": CONCEPT},
            {"name": "羟甲基戊二酰辅酶A还原酶", "type": MECH},
            {"name": "低密度脂蛋白胆固醇", "type": CONCEPT},
            {"name": "低密度脂蛋白受体", "type": MECH},
            {"name": "高胆固醇血症", "type": DISEASE},
            {"name": "混合型高脂血症", "type": DISEASE},
            {"name": "动脉粥样硬化性心血管疾病", "type": DISEASE},
            {"name": "肌肉疼痛", "type": SE},
            {"name": "肝酶升高", "type": SE},
            {"name": "头痛", "type": SE},
            {"name": "肌病", "type": SE},
            {"name": "阿斯利康公司", "type": COMPANY},
            {"name": "阿托伐他汀", "type": DRUG},
        ],
        "relationships": [
            {"source": "瑞舒伐他汀", "target": "羟甲基戊二酰辅酶A还原酶", "type": "作用于"},
            {"source": "瑞舒伐他汀", "target": "低密度脂蛋白胆固醇", "type": "作用于"},
            {"source": "瑞舒伐他汀", "target": "高胆固醇血症", "type": "治疗"},
            {"source": "瑞舒伐他汀", "target": "混合型高脂血症", "type": "治疗"},
            {"source": "瑞舒伐他汀", "target": "动脉粥样硬化性心血管疾病", "type": "治疗"},
            {"source": "瑞舒伐他汀", "target": "肌肉疼痛", "type": "副作用"},
            {"source": "瑞舒伐他汀", "target": "肝酶升高", "type": "副作用"},
            {"source": "瑞舒伐他汀", "target": "头痛", "type": "副作用"},
            {"source": "瑞舒伐他汀", "target": "肌病", "type": "副作用"},
            {"source": "瑞舒伐他汀", "target": "他汀类", "type": "属于"},
            {"source": "阿斯利康公司", "target": "瑞舒伐他汀", "type": "研发"},
            {"source": "阿托伐他汀", "target": "高脂血症", "type": "治疗"},
        ],
    },
    "clarithromycin.txt": {
        "entities": [
            {"name": "克拉霉素", "type": DRUG},
            {"name": "大环内酯类", "type": CONCEPT},
            {"name": "核糖体50S亚基", "type": MECH},
            {"name": "蛋白质合成", "type": CONCEPT},
            {"name": "呼吸道感染", "type": DISEASE},
            {"name": "鼻窦炎", "type": DISEASE},
            {"name": "中耳炎", "type": DISEASE},
            {"name": "皮肤感染", "type": DISEASE},
            {"name": "幽门螺杆菌", "type": CONCEPT},
            {"name": "恶心", "type": SE},
            {"name": "腹泻", "type": SE},
            {"name": "腹痛", "type": SE},
            {"name": "味觉异常", "type": SE},
            {"name": "肝酶升高", "type": SE},
            {"name": "雅培公司", "type": COMPANY},
        ],
        "relationships": [
            {"source": "克拉霉素", "target": "核糖体50S亚基", "type": "作用于"},
            {"source": "克拉霉素", "target": "呼吸道感染", "type": "治疗"},
            {"source": "克拉霉素", "target": "鼻窦炎", "type": "治疗"},
            {"source": "克拉霉素", "target": "中耳炎", "type": "治疗"},
            {"source": "克拉霉素", "target": "皮肤感染", "type": "治疗"},
            {"source": "克拉霉素", "target": "幽门螺杆菌", "type": "治疗"},
            {"source": "克拉霉素", "target": "恶心", "type": "副作用"},
            {"source": "克拉霉素", "target": "腹泻", "type": "副作用"},
            {"source": "克拉霉素", "target": "腹痛", "type": "副作用"},
            {"source": "克拉霉素", "target": "味觉异常", "type": "副作用"},
            {"source": "克拉霉素", "target": "肝酶升高", "type": "副作用"},
            {"source": "克拉霉素", "target": "大环内酯类", "type": "属于"},
            {"source": "雅培公司", "target": "克拉霉素", "type": "研发"},
        ],
    },
    "budesonide.txt": {
        "entities": [
            {"name": "布地奈德", "type": DRUG},
            {"name": "吸入性糖皮质激素", "type": CONCEPT},
            {"name": "糖皮质激素受体", "type": MECH},
            {"name": "气道炎症", "type": CONCEPT},
            {"name": "哮喘", "type": DISEASE},
            {"name": "慢性阻塞性肺疾病", "type": DISEASE},
            {"name": "过敏性鼻炎", "type": DISEASE},
            {"name": "口腔念珠菌感染", "type": SE},
            {"name": "声音嘶哑", "type": SE},
            {"name": "咽部刺激", "type": SE},
            {"name": "阿斯利康公司", "type": COMPANY},
            {"name": "沙丁胺醇", "type": DRUG},
        ],
        "relationships": [
            {"source": "布地奈德", "target": "糖皮质激素受体", "type": "作用于"},
            {"source": "布地奈德", "target": "哮喘", "type": "治疗"},
            {"source": "布地奈德", "target": "慢性阻塞性肺疾病", "type": "治疗"},
            {"source": "布地奈德", "target": "过敏性鼻炎", "type": "治疗"},
            {"source": "布地奈德", "target": "气道炎症", "type": "作用于"},
            {"source": "布地奈德", "target": "口腔念珠菌感染", "type": "副作用"},
            {"source": "布地奈德", "target": "声音嘶哑", "type": "副作用"},
            {"source": "布地奈德", "target": "咽部刺激", "type": "副作用"},
            {"source": "布地奈德", "target": "吸入性糖皮质激素", "type": "属于"},
            {"source": "阿斯利康公司", "target": "布地奈德", "type": "研发"},
            {"source": "沙丁胺醇", "target": "哮喘", "type": "治疗"},
        ],
    },
    "ezetimibe.txt": {
        "entities": [
            {"name": "依折麦布", "type": DRUG},
            {"name": "胆固醇吸收抑制剂", "type": CONCEPT},
            {"name": "尼曼-匹克C1型类似蛋白1", "type": MECH},
            {"name": "小肠刷状缘", "type": CONCEPT},
            {"name": "胆固醇", "type": CONCEPT},
            {"name": "高胆固醇血症", "type": DISEASE},
            {"name": "头痛", "type": SE},
            {"name": "腹泻", "type": SE},
            {"name": "腹痛", "type": SE},
            {"name": "默沙东公司", "type": COMPANY},
            {"name": "阿托伐他汀", "type": DRUG},
        ],
        "relationships": [
            {"source": "依折麦布", "target": "尼曼-匹克C1型类似蛋白1", "type": "作用于"},
            {"source": "依折麦布", "target": "高胆固醇血症", "type": "治疗"},
            {"source": "依折麦布", "target": "胆固醇", "type": "作用于"},
            {"source": "依折麦布", "target": "头痛", "type": "副作用"},
            {"source": "依折麦布", "target": "腹泻", "type": "副作用"},
            {"source": "依折麦布", "target": "腹痛", "type": "副作用"},
            {"source": "依折麦布", "target": "胆固醇吸收抑制剂", "type": "属于"},
            {"source": "默沙东公司", "target": "依折麦布", "type": "研发"},
            {"source": "阿托伐他汀", "target": "高胆固醇血症", "type": "治疗"},
        ],
    },
    "warfarin.txt": {
        "entities": [
            {"name": "华法林", "type": DRUG},
            {"name": "香豆素类", "type": CONCEPT},
            {"name": "维生素K环氧化物还原酶", "type": MECH},
            {"name": "凝血因子II", "type": CONCEPT},
            {"name": "凝血因子VII", "type": CONCEPT},
            {"name": "凝血因子IX", "type": CONCEPT},
            {"name": "凝血因子X", "type": CONCEPT},
            {"name": "深静脉血栓", "type": DISEASE},
            {"name": "肺栓塞", "type": DISEASE},
            {"name": "心房颤动", "type": DISEASE},
            {"name": "脑卒中", "type": DISEASE},
            {"name": "出血", "type": SE},
            {"name": "鼻出血", "type": SE},
            {"name": "牙龈出血", "type": SE},
            {"name": "颅内出血", "type": SE},
            {"name": "凝血指标", "type": CONCEPT},
        ],
        "relationships": [
            {"source": "华法林", "target": "维生素K环氧化物还原酶", "type": "作用于"},
            {"source": "华法林", "target": "深静脉血栓", "type": "治疗"},
            {"source": "华法林", "target": "肺栓塞", "type": "治疗"},
            {"source": "华法林", "target": "心房颤动", "type": "治疗"},
            {"source": "华法林", "target": "脑卒中", "type": "治疗"},
            {"source": "华法林", "target": "出血", "type": "副作用"},
            {"source": "华法林", "target": "鼻出血", "type": "副作用"},
            {"source": "华法林", "target": "牙龈出血", "type": "副作用"},
            {"source": "华法林", "target": "颅内出血", "type": "副作用"},
            {"source": "华法林", "target": "凝血因子II", "type": "作用于"},
            {"source": "华法林", "target": "凝血因子VII", "type": "作用于"},
            {"source": "华法林", "target": "凝血因子IX", "type": "作用于"},
            {"source": "华法林", "target": "凝血因子X", "type": "作用于"},
            {"source": "华法林", "target": "香豆素类", "type": "属于"},
            {"source": "华法林", "target": "凝血指标", "type": "作用于"},
        ],
    },
}
